@url = http://localhost:3610

### GET INFO
GET {{url}}

### GET ALL BOOKS
GET {{url}}/books

### GET SPECIFIC BOOK
GET {{url}}/book/62c3fca5997884b0fdda415a

### ADD BOOK
POST {{url}}/book
content-type: application/json

{
  "title": "Added Book2",
  "description": "lorem ipsum dolor sit amet, consectetur, lorem ipsum dolor sit amet, lorem ipsum dolor sit amet",
  "numberOfPages": 999,
  "language": "english",
  "imageUrl": "http://test.com",
  "buyUrl": "http://test.com"
}
